### ISSUE TITLE
Support for dashed lines

### ISSUE THREAD

**Issue by omrivolk** [bojko108/ol-esri-style#12]
Dashed line with label such esriSLSDash are rendered as solid lines. Is there support for dashed lines?

**Comment by bojko108** [comment]
Hi, 
you are correct, the default style is solid line. You are talking about this style: [Simple Line Symbol](https://developers.arcgis.com/documentation/common-data-types/symbol-objects.htm#GUID-EA27E7EA-1995-4B04-9913-601F1F46A53D), right? 

OpenLayers support rendering of dashed lines, but I'm not sure how the dash pattern is defined in EsriJSON. As you can see there is only one property - `style: esriSLSDash | esriSLSDashDot ...` in ESRI style definition, and there are no properties, which define the dash pattern. Maybe we can define some constant dash patterns for each ESRI style value (`esriSLSDash`, `esriSLSDashDot` etc.) and use them when creating the OL style. 

Take a look at this example: [https://codesandbox.io/s/esri-dashed-lines-05hug](https://codesandbox.io/s/esri-dashed-lines-05hug).  Each line has different `lineDash` value, depending on the ESRI Simple Line Symbol.

**Comment by omrivolk** [comment]
Your example looks like a great solution for `esriSLSDash | esriSLSDashDot | esriSLSDashDotDot | esriSLSDot` ! and would be great to have.

I've noticed that there are other more complex types of lines such as double lines and lines with direction triangles:
![Screen Shot 2021-02-06 at 4 56 05 PM](https://user-images.githubusercontent.com/10728346/107121665-65f9f900-689c-11eb-9b75-307bd7d34e68.png)
But the rest server doesn't actually give any information about this,  wonder if something could be done.

**Comment by bojko108** [comment]
Yes, right now this package is very limited but in the future it can support more complex symbols. It will be great if there is a public ArcGIS Service or if you can send me the definition of these symbols in EsriJSON format. 

P.S. I'll implement the solution for the dashed lines soon.
