### ISSUE TITLE
Inner global variable would cause problems if library is used in multiple views

### ISSUE THREAD

**Issue by categulario** [bojko108/ol-esri-style#30]
the `setMapProjection` function alters a global variable that is shared among all uses of this library. This means that if a second map with a different projection is shown on the same page the second call to this function would replace the private `mapProjection` value and perhaps cause problems with labels for the first map.

I think a better approach would be for the `createStyleFunction[fromUrl]` functions to accept an optional `projection` parameter the user can pass if labels are in use.

Of course that would be a breaking change (because API changes).

If this is acceptable I would be happy to make a pull request.

And thanks for this amazing work (:

**Comment by bojko108** [comment]
Hi, 
I completely agree with you, this is something I wanted to do before, but just forgot about it. If it's ok for you, make the change.

**Comment by apeling** [comment]
This should have been pushed as a major release and not a minor as it is not backwards compatible.

**Comment by bojko108** [comment]
Sorry about that, but I don't publish often. Should I publish a new major release? Maybe I should make a patch release with introducing the `setMapProjection` method back and then a major one removing it? Is that the right approach?

**Comment by apeling** [comment]
We're updating our library. I'm not sure of the best path for other developers. However, keeping 2.2.0 it as is will surprise break pipelines with semantic versioning that allows minor.

**Comment by bojko108** [comment]
So sorry for this, I should be more careful in the future. I've published two new releases:

- **v2.2.1** - patch release where both methods can be used: 
   - set map projection with `setMapProjection(projection)`
   - or pass the map projection in `createStyleFunctionFromUrl(...)` or `createStyleFunction(...)`
- **v.3.0.0** - major release where the `setMapProjection(projection)` is removed
