### ISSUE TITLE
Openlayers - georeferencing with affine function

### ISSUE THREAD

**Issue by patrykkalinowski** [bojko108/ol-esri-style#33]
Hi Bogdan,
Sorry for creating an issue, but I couldn't find any other way to directly contact you.

I stumbled upon your question on SO: https://stackoverflow.com/questions/52904587/displaying-georeferenced-images-using-openlayers-5

I'm trying to do the same thing (georeference rotated maps in openlayers). I was wondering how Affine.js (https://codesandbox.io/s/kw9l85y5po?file=/src/Affine.js) is working under the hood. Is there any explanation for the calculations I could read and understand how it works?
Also, in your code there is no inverse function. Would calling the existing `Affine.calculate` function with reversed arguments do the trick?

Thanks and sorry for offtopic issue,
Patryk

**Comment by bojko108** [comment]
Hi Patryk, 
this one is very old :) Unfortunately I'm not able to help you with that. The code was taken from an existing project in C# and there is no more info about it. You are right that calling the method with reversed parameters will give you the inverse parameters for the transformation.
