### ISSUE TITLE
Symbols with 'Falsy' Values are not being rendered

### ISSUE THREAD

**Issue by dev-cp-a** [bojko108/ol-esri-style#35]
# Falsy Feature Attribute Values Incorrectly Coerced to Empty String

## Issue Description
When a feature has falsy values (undefined, null, 0, etc.) for attributes, these values are currently being coerced to an empty string (`''`). This causes symbols not to be rendered correctly when the style depends on these attributes.

The following code is in `src/index.js` at line 56

## Current Behavior
In the current implementation, the code handles feature attributes like this:
```js
const currentValue = feature.get(field) || '';
```

This results in all falsy values being replaced with an empty string due to the OR (||) operator's behavior in JavaScript.

## Expected Behavior
'Falsy' values should be preserved as-is (in the case for the number 0 (zero), for example) unless they are explicitly undefined or null, in which case they should be coerced to an empty string.

## Fix
I've modified the code to only coerce undefined and null values to empty strings:
```js
let currentValue = feature.get(field);
if (currentValue === undefined || currentValue === null) {
    currentValue = '';
}
```

**Comment by bojko108** [comment]
Hello, I agree with you, can you make a pull request with this change?
